POST http://127.0.0.1:3010/api/reports/policies/indiv
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYWRpYW50dGVzdCIsInNjb3BlcyI6IkFETUlOIiwiaWF0IjoxNjEzMDQwOTI4LCJleHAiOjE2MTM2NDU3Mjh9.XA1V2A2PhHIF9OtS_oDFxY6unyPT_7SPbo2Xou9WxKs 

{
    "startDate": "2020-01-01",
    "endDate": "2021-01-01"
}

###